### ISSUE TITLE
Issue building on Indigo

### ISSUE THREAD

**Issue by Jrokisky** [SteveMacenski/nonpersistent_voxel_layer#1]
I ran into an issue while trying to use this node on ROS Indigo on a Jetson TK1.
Catkin_make would fail as it was unable to find NonPersistentVoxelPluginConfig.h

In the CMake file I added:
`add_dependencies(nonpersistent_voxel_layer ${PROJECT_NAME}_gencfg)`
above:
`target_link_libraries(nonpersistent_voxel_layer ${catkin_LIBRARIES})`
which fixed the issue.

I am not sure if this is an issue with my local setup or not, but figured I would open an issue to document this in case anyone else ran into a similar issue.

**Comment by SteveMacenski** [comment]
Awesome! Thanks for the help. I have had that happen to be on rare occasions but usually a `catkin clean` and `catkin build` resolved it. I would love if you PRed those changes!
