### ISSUE TITLE
Costmap is inconsistent

### ISSUE THREAD

**Issue by stevemartinov** [SteveMacenski/nonpersistent_voxel_layer#17]
Hi,

I am using new TI mmWave radar called IWR6843AOP and I have configured my costmap plugin to be like this:

```
radar_layer:
  enabled:              true
  track_unknown_space:  true
  max_obstacle_height:  2.0
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   0
  obstacle_range: 3.0
  origin_z: 0.0
  z_resolution: 0.5
  z_voxels: 16
  publish_voxel_map: true
  observation_sources: rgbd
  rgbd:
    data_type: PointCloud2
    topic: /radar1/RScan
    marking: true
    min_obstacle_height: -0.5
    max_obstacle_height: 2.0
```

However, it seems to me that the costs do not appear to be staying for long enough to have a safe navigation and very often the plugin just does not register the obstacles even when there are enough point clouds.

I am also attaching a rosbag:
https://drive.google.com/file/d/14DnreKRNoLC5uTthm80YmWMA7RQp6oIj/view?usp=sharing

Also I tried to use the `spatio_temporal_voxel_layer` and it worked much better but as TI is a radar, I thought may be this plugin suits it better and I am doing something wrong.

**Comment by SteveMacenski** [comment]
> it seems to me that the costs do not appear to be staying for long enough 

Please read this package's description. It is only storing 1 data measurement for 1 update cycle. If that's not what you want, then you should not use this package.
