### ISSUE TITLE
Costmap with 2d lidar

### ISSUE THREAD

**Issue by AlessandroMelino** [SteveMacenski/nonpersistent_voxel_layer#18]
Hello.

Is it possible to use this package for marking obstacles with a 2d Lidar? If it is, how would be the layer configuration on the costmap common params?

Best regards.
Alessandro

**Comment by SteveMacenski** [comment]
Yes you may but the obstacle layer may be a better option for you.

**Comment by AlessandroMelino** [comment]
> Yes you may but the obstacle layer may be a better option for you.

I know, but the problem with obstacle layer is the clearing, it does not make it very well, and so many obstacles remain in the map.

This is the reason I want to use non persisting or spatio temporal layer (in Noetic).

Best regards.

**Comment by SteveMacenski** [comment]
Ok
