### ISSUE TITLE
Remove PCL dependency

### ISSUE THREAD

**Issue by reinzor** [SteveMacenski/nonpersistent_voxel_layer#19]
Hi,

Would you accept a PR where we remove the dependency on PCL ([[1]](https://github.com/SteveMacenski/nonpersistent_voxel_layer/blob/foxy-devel/package.xml#L23), [[2]](https://github.com/SteveMacenski/nonpersistent_voxel_layer/blob/foxy-devel/package.xml#L33))? When I install this package on a clean `ros:noetic-ros-base` image, it tries to install `2260 MB` and I figured out it is due to the `PCL` dependencies.

As far as I can see, PCL is only used here for converting the pointcloud2 message to a c++ structure we can work with but this can also be done using the [PointCloud2Iterator](http://docs.ros.org/en/jade/api/sensor_msgs/html/classsensor__msgs_1_1PointCloud2Iterator.html) in the `sensor_msgs` package.

What do you think?

**Comment by reinzor** [comment]
I see you already implemented a workaround for this in the `ros2` branch. However, in order to sync the `ros1` / `ros2` branches, I also created a PR for `ros2` for removing the `PCL` deps.

**Comment by SteveMacenski** [comment]
Sounds good to me, I have no issue with that.
