### ISSUE TITLE
build with Melodic

### ISSUE THREAD

**Issue by SteveMacenski** [SteveMacenski/nonpersistent_voxel_layer#3]

**Comment by reinzor** [comment]
- #6 Should add Melodic support
- #7 Should add CI in order to test the build against `Kinetic` and `Melodic` using Industrial CI.

**Comment by reinzor** [comment]
ping

**Comment by SteveMacenski** [comment]
Hi thanks for following up, its been a crazy couple weeks, I'll get to these today.
